Pandas Library:

Useful for Data Processing & Analysis

In [6]:
pip install --upgrade pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\manth\appdata\roaming\python\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in c:\users\manth\appdata\roaming\python\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [12]:
# importing the pandas library
import pandas as pd
import numpy as np
import seaborn as sns

Creating a Pandas DataFrame

In [13]:
df = sns.load_dataset("flights")

In [14]:
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [15]:
df.shape

(144, 3)

Importing the data from a CSV file to a pandas DataFrame

In [17]:
# csv file to pandas df
df = pd.read_csv('titanic_train_data.csv')

In [18]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
df.shape

(891, 12)

Loading the data from a excel file to a Pandas DataFrame:

pd.read_excel('file path')

Exporting a DataFrame to a csv file

In [22]:
df.to_csv('titanic.csv')

Exporting the Pandas DataFrame to an excel File:

df.to_excel('filename')

In [23]:
# creating a DatFrame with random values
random_df = pd.DataFrame(np.random.rand(20,10))

In [24]:
random_df.head()

,0,1,2,3,4,5,6,7,8,9
0,0.179448,0.182513,0.600340,0.607182,0.347431,0.724694,0.149353,0.716968,0.371203,0.392450
1,0.432251,0.202588,0.532574,0.284938,0.648858,0.129206,0.516620,0.177299,0.921669,0.316064
2,0.703045,0.690556,0.858437,0.958825,0.222432,0.006730,0.818403,0.547557,0.925727,0.139497
3,0.013704,0.107147,0.869869,0.053491,0.849674,0.236695,0.058749,0.175864,0.321855,0.521111
4,0.050791,0.258554,0.722299,0.853939,0.181912,0.519511,0.566294,0.628987,0.107672,0.694119

In [25]:
random_df.shape

(20, 10)

Inspecting a DataFrame

In [26]:
#finding the number of rows & columns
df.shape

(891, 12)

In [28]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [29]:
# last 5 rows of the DataFrame
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [30]:
# informations about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [31]:
# finding the number of missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
boston_df = pd.read_csv("housing.csv")

In [58]:
# iris dataframe
boston_df.head()

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [59]:
# counting the values based on the labels
boston_df.value_counts()

RM     LSTAT  PTRATIO  MEDV
3.561  7.12   20.2     577500.0     1
6.454  14.59  21.2     359100.0     1
6.442  8.16   18.2     480900.0     1
6.438  3.59   19.1     520800.0     1
6.437  14.36  20.2     487200.0     1
                                   ..
5.966  14.44  19.7     336000.0     1
       10.13  19.2     518700.0     1
5.965  13.83  21.0     411600.0     1
5.963  13.45  16.8     413700.0     1
8.398  5.91   13.0     1024800.0    1
Name: count, Length: 489, dtype: int64

Statistical Measures

In [60]:
# count or number of values
boston_df.count()

RM         489
LSTAT      489
PTRATIO    489
MEDV       489
dtype: int64

In [61]:
# all the statistical measures about the dataframe
boston_df.describe()

               RM       LSTAT     PTRATIO          MEDV
count  489.000000  489.000000  489.000000  4.890000e+02
mean     6.240288   12.939632   18.516564  4.543429e+05
std      0.643650    7.081990    2.111268  1.653403e+05
min      3.561000    1.980000   12.600000  1.050000e+05
25%      5.880000    7.370000   17.400000  3.507000e+05
50%      6.185000   11.690000   19.100000  4.389000e+05
75%      6.575000   17.120000   20.200000  5.187000e+05
max      8.398000   37.970000   22.000000  1.024800e+06

Manipulating a DataFrame

In [62]:
# adding a column to a dataframe
boston_df['Price'] = boston_dataset.target

NameError: name 'boston_dataset' is not defined

In [63]:
boston_df.head()

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [64]:
# removing a row
boston_df.drop(index=0, axis=0)

        RM  LSTAT  PTRATIO      MEDV
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
5    6.430   5.21     18.7  602700.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[488 rows x 4 columns]

In [68]:
# drop a column
boston_df.drop(columns='PTRATIO', axis=1)

        RM  LSTAT      MEDV
0    6.575   4.98  504000.0
1    6.421   9.14  453600.0
2    7.185   4.03  728700.0
3    6.998   2.94  701400.0
4    7.147   5.33  760200.0
..     ...    ...       ...
484  6.593   9.67  470400.0
485  6.120   9.08  432600.0
486  6.976   5.64  501900.0
487  6.794   6.48  462000.0
488  6.030   7.88  249900.0

[489 rows x 3 columns]

In [66]:
# locating a row using the index value
boston_df.iloc[2]

RM              7.185
LSTAT           4.030
PTRATIO        17.800
MEDV       728700.000
Name: 2, dtype: float64

In [67]:
# locating a particular column
print(boston_df.iloc[:,0])  # first column
print(boston_df.iloc[:,1])  # second column
print(boston_df.iloc[:,2])  # third column
print(boston_df.iloc[:,-1]) # last column

0      6.575
1      6.421
2      7.185
3      6.998
4      7.147
       ...
484    6.593
485    6.120
486    6.976
487    6.794
488    6.030
Name: RM, Length: 489, dtype: float64
0      4.98
1      9.14
2      4.03
3      2.94
4      5.33
       ...
484    9.67
485    9.08
486    5.64
487    6.48
488    7.88
Name: LSTAT, Length: 489, dtype: float64
0      15.3
1      17.8
2      17.8
3      18.7
4      18.7
       ...
484    21.0
485    21.0
486    21.0
487    21.0
488    21.0
Name: PTRATIO, Length: 489, dtype: float64
0      504000.0
1      453600.0
2      728700.0
3      701400.0
4      760200.0
         ...
484    470400.0
485    432600.0
486    501900.0
487    462000.0
488    249900.0
Name: MEDV, Length: 489, dtype: float64

Correlation:

1. Positive Correlation
2. Negative Correlation