In [4]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Iris.csv")

In [3]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df = df.rename(columns={"SepalLengthCm" : "Sepal_length" , "PetalWidthCm" : "Petal_width" , "SepalWidthCm" : "Sepal_width" ,"PetalLengthCm" : "Petal_length"})

In [6]:
df.shape

(150, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            150 non-null    int64
 1   Sepal_length  150 non-null    float64
 2   Sepal_width   150 non-null    float64
 3   Petal_length  150 non-null    float64
 4   Petal_width   150 non-null    float64
 5   Species       150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [8]:
df.head()

   Id  Sepal_length  Sepal_width  Petal_length  Petal_width      Species
0   1           5.1          3.5           1.4          0.2  Iris-setosa
1   2           4.9          3.0           1.4          0.2  Iris-setosa
2   3           4.7          3.2           1.3          0.2  Iris-setosa
3   4           4.6          3.1           1.5          0.2  Iris-setosa
4   5           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
df.duplicated().sum()

0

In [10]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [11]:
df.drop(columns=["Id"], inplace = True)

In [12]:
df

     Sepal_length  Sepal_width  Petal_length  Petal_width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [14]:
X = df.drop(columns=["Species"])
y = df["Species"]

In [15]:
X

     Sepal_length  Sepal_width  Petal_length  Petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [16]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = None, test_size=0.2)

In [18]:
print(X_train.shape , X_test.shape)

(120, 4) (30, 4)

In [19]:
print(y_train.shape , y_test.shape)

(120,) (30,)

In [20]:
model = LogisticRegression()

In [21]:
model.fit(X_train, y_train)

LogisticRegression()

In [22]:
X_train_pred = model.predict(X_train)
training_accuracy = accuracy_score(X_train_pred, y_train)

In [23]:
print("Accuracy on Training data : ", training_accuracy*100)

Accuracy on Training data :  96.66666666666667

In [24]:
X_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(X_test_pred, y_test)

In [25]:
print(classification_report(y_test, X_test_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

In [26]:
print(confusion_matrix(y_test, X_test_pred))

[[ 8  0  0]
 [ 0  9  0]
 [ 0  0 13]]

In [27]:
print("Accuracy on Testing data : ", test_accuracy*100)

Accuracy on Testing data :  100.0

In [1]:
input_dict = {
    'Sepal_length': 6.8,
    'Sepal_width':  3.5,
    'Petal_length': 5.2,
    'Petal_width': 1.4
}

In [5]:
input_df = pd.DataFrame([input_dict])

In [8]:
predicted_class = model.predict(input_df)

In [9]:
print("Predicted Species :", predicted_class)

Predicted Species : ['Iris-versicolor']

In [35]:
import pickle

with open('iris_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [7]:
import pickle

with open('iris_model.pkl', 'rb') as file:
    model = pickle.load(file)